version: '3.9'
services:
  app:
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - ./app/static/output:/app/static/output
      - ./mlruns:/mlruns 

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.12.1
    command: mlflow ui --backend-store-uri /mlruns --host 0.0.0.0 --port 5001
    ports:
      - "5001:5001"
    volumes:
      - ./mlruns:/mlruns